### ISSUE TITLE
Possible issues with STL files?

### ISSUE THREAD

**Issue by xoxota99** [projectfdl/FDL-3-Blaster#8]
I'm intending to print my own FDL-3 (shorty nose, full-auto tail), and noticed a couple of things in the STL files that I'm not sure if they are issues or not. Could you help me understand whether this is intentional, or if I need to "fix" them somehow?

in STL/Tail Auto:
- **Pusher Housing Main.stl** : Seems to have no holes for the motor shaft or mounting screws.
- **Pusher Housing Cap.stl**: Seems to have little bits of flashing around the outside of the part, where the cutouts are.
- **Handle Scale L.stl**: Has some sort of 0.2mm-thick rectangle hanging off the end of it (toward the front of the blaster).
- **Handle Scale R.stl**: Same issue as above. Weird rectangle on the front end of it.
- **PCB Mount.stl**: Seems to have a thin strip of plastic across the bottom-front of the model, across the cutout below the mount for the power switch.

In the STEP files:
- There are a couple of extra parts (basically flat rectangles) underneath the PCB (inside the "PCB Mount" part) in the "FDL-3_Tail Auto" design that were not exported as STL files. Are these not needed?
- Bunch of miscellaneous floating screw heads in the "FDL-3_Tail Semi" design.

**Comment by 43sunsets** [comment]
@xoxota99 For the **Pusher Housing**, it lacks holes because you're meant to drill these out after printing. This allows the part to be printed without supports. If you lack a drill (like me), you can modify the STLs to have actual holes, and print the part with supports instead.

For everything else STL, the "bits of flashing" or thin strips of extra plastic are meant to act as selective brims, to aid bed adhesion -- or at least, that's my interpretation. You can cut these off using flush cutters after printing.

**Comment by xoxota99** [comment]
Thanks! I wasn't sure if I should remove them, but I couldn't see how they were used in the STEP files. "selective brims" is a great idea, and makes sense.

What about those two mysterious rectangular plates under the pcb in the "Tail Auto" STEP file? Do I need those? They don't have a corresponding STL file.

**Comment by 43sunsets** [comment]
@xoxota99 Sorry, I'm not familiar with STEP files and loading it up in F360 I have no idea how to separate the components to view them so I'm not sure what the rectangular plates are. But if they're not amongst the STL files then you don't need to print them.

**Comment by zafuquazar** [comment]
@xoxota99, can I ask you where you found the STEP files? In teh CAD folder, there are only .dwg files, which I cannot actually open in F360 - they open in a browser window only (even after uploading to F360). Thanks!

**Comment by xoxota99** [comment]
@zafuquazar Good question! I know I downloaded them at some point (and have them in a Fusion 360 project), but now I can't find them anywhere on the web.

I've reached out to Jackie, to ask for permission to share the files I have. I'll let you know if/when I hear back.

**Comment by zafuquazar** [comment]
Thank you very much! I would like to make a blaster using the motors that I already have, and I would love to work from the FDL3 STEP files so I don't have to model everything from scratch :)

**Comment by 43sunsets** [comment]
> @xoxota99, can I ask you where you found the STEP files? In teh CAD folder, there are only .dwg files, which I cannot actually open in F360

I can confirm that Fusion 360 can read DWG files, you need to **Upload** them as a new project. There's no STEP files because the DWG files are it.

**Comment by zafuquazar** [comment]
Thanks!
Hmm, ok, maybe I am doing it wrong. I did create a new project in F360 and upload the .dwg files. But when i try to open them, they open in a a browser window instead of F360. I can view rotate, etc in the browser, but cannot edit them. 
But perhaps I’m doing something wrong - I’ll try again.

**Comment by 43sunsets** [comment]
@zafuquazar Hmm yeah that's really odd, it shouldn't be opening in a browser at all, it should remain and open within F360. Good luck, hope you can get it working soon!

**Comment by zafuquazar** [comment]
Ok, thanks! I use Solidworks at work every day, but I feel pretty noob-ish in F360. I’ll keep at it!

**Comment by stukemanmini** [comment]
> Thank you very much! I would like to make a blaster using the motors that I already have, and I would love to work from the FDL3 STEP files so I don't have to model everything from scratch :)

I made a few small changes in F360 to my blaster before printing. Here's how I've done it:
Use the "Insert Mesh" to import the STL file as a wireframe. 
Tell the project to "Do not capture design history". (This seems to be required to convert a wireframe to a solid body)
Use the "Convert to BRep" on the mesh to make the wireframe into a body.
Then re-enable the design history.

**Comment by xoxota99** [comment]
@43sunsets Slight correction. Fusion360 *used to* be able to import .DWG files (back when I did it in September). They have recently introduced new licensing terms for hobbyists that removed this capability. Fortunately, I still have my original imported project, and Jackie has given me permission to share them as a one-off.

@zafuquazar I'll email a zip file with the exported STEP files to the email address in your github profile. Hope this helps.

**Comment by xoxota99** [comment]
I'm going to resolve this issue, since the question has been answered. Thanks!

**Comment by zafuquazar** [comment]
@xoxota99 And @43sunsets, thank you so much for your help! I did try again today and could not get the parts to open inside of F360 - I’m happy to know I’m not crazy :)

**Comment by 43sunsets** [comment]
> @43sunsets Slight correction. Fusion360 _used to_ be able to import .DWG files (back when I did it in September). They have recently introduced new licensing terms for hobbyists that removed this capability. 

Oh I wasn't aware of that, that sucks that they did that 😰. I thought I was using the Hobbyist version but it turns out I'm on the Student version of F360, so that probably explains it.
